{"uid":"e8b5ae9f0a1eb0eb","name":"Тест заранее проваленный у авторизованного пользователя","fullName":"tests.test_product_page.TestUserAddToBasketFromProductPage#test_user_cant_see_success_message_after_adding_product_to_basket","historyId":"dd1b607429d5a84eee79e87766c27d6c","time":{"start":1743401122972,"stop":1743401122972,"duration":0},"description":"Открываем страницу товара \n        Добавляем товар в корзину \n        Проверяем, что нет сообщения об успехе с помощью is_not_element_present","descriptionHtml":"<p>Открываем страницу товара<br />\nДобавляем товар в корзину<br />\nПроверяем, что нет сообщения об успехе с помощью is_not_element_present</p>\n","status":"skipped","statusMessage":"XFAIL Now not work!\n\nAssertionError: User icon is not presented, probably unauthorised user","statusTrace":"E   AssertionError: User icon is not presented, probably unauthorised user","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1743401105052,"stop":1743401105109,"duration":57},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"browser","time":{"start":1743401122973,"stop":1743401123296,"duration":323},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"setup","time":{"start":1743401123296,"stop":1743401134446,"duration":11150},"status":"failed","statusMessage":"AssertionError: User icon is not presented, probably unauthorised user\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/project_selenium_course/project_selenium_course/tests/test_product_page.py\", line 19, in setup\n    login_page.should_be_authorized_user()\n  File \"/home/runner/work/project_selenium_course/project_selenium_course/pages/base_page.py\", line 74, in should_be_authorized_user\n    assert self.is_element_present(*BasePageLocators.USER_ICON), \"User icon is not presented, probably unauthorised user\"\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"testStage":{"description":"Открываем страницу товара \n        Добавляем товар в корзину \n        Проверяем, что нет сообщения об успехе с помощью is_not_element_present","status":"skipped","statusMessage":"XFAIL Now not work!\n\nAssertionError: User icon is not presented, probably unauthorised user","statusTrace":"E   AssertionError: User icon is not presented, probably unauthorised user","steps":[],"attachments":[{"uid":"eb80d745b1bb02d7","name":"stdout","source":"eb80d745b1bb02d7.txt","type":"text/plain","size":89}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"browser::0","time":{"start":1743401134449,"stop":1743401134515,"duration":66},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"feature","value":"Product"},{"name":"story","value":"Product Feature"},{"name":"tag","value":"@pytest.mark.xfail(reason='Now not work!')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_product_page"},{"name":"subSuite","value":"TestUserAddToBasketFromProductPage"},{"name":"host","value":"fv-az1971-525"},{"name":"thread","value":"2399-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_product_page"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":0,"skipped":8,"passed":0,"unknown":0,"total":8},"items":[{"uid":"b2a94b4fcf8deac2","reportUrl":"https://Lexun2.github.io/project_selenium_course/22//#testresult/b2a94b4fcf8deac2","status":"skipped","statusDetails":"XFAIL Now not work!\n\nAssertionError: Success message(NAME_ITEM_IN_MESSAGE) is presented, but should not be","time":{"start":1743400064804,"stop":1743400065898,"duration":1094}},{"uid":"bd34f9a3aa9a7910","reportUrl":"https://Lexun2.github.io/project_selenium_course/21//#testresult/bd34f9a3aa9a7910","status":"skipped","statusDetails":"XFAIL Now not work!\n\nAssertionError: Success message(NAME_ITEM_IN_MESSAGE) is presented, but should not be","time":{"start":1743399765393,"stop":1743399766594,"duration":1201}},{"uid":"a81aa11baea1fc2d","reportUrl":"https://Lexun2.github.io/project_selenium_course/20//#testresult/a81aa11baea1fc2d","status":"skipped","statusDetails":"XFAIL Now not work!\n\nAssertionError: Success message(NAME_ITEM_IN_MESSAGE) is presented, but should not be","time":{"start":1743398409300,"stop":1743398410308,"duration":1008}},{"uid":"8d7c41f9619150b5","reportUrl":"https://Lexun2.github.io/project_selenium_course/19//#testresult/8d7c41f9619150b5","status":"skipped","statusDetails":"XFAIL Now not work!\n\nAssertionError: Success message(NAME_ITEM_IN_MESSAGE) is presented, but should not be","time":{"start":1743066023131,"stop":1743066025090,"duration":1959}},{"uid":"b58fd29624212b61","reportUrl":"https://Lexun2.github.io/project_selenium_course/18//#testresult/b58fd29624212b61","status":"skipped","statusDetails":"XFAIL Now not work!\n\nAssertionError: Success message(NAME_ITEM_IN_MESSAGE) is presented, but should not be","time":{"start":1742892179824,"stop":1742892180842,"duration":1018}},{"uid":"21d70106f3a07c7","reportUrl":"https://Lexun2.github.io/project_selenium_course/17//#testresult/21d70106f3a07c7","status":"skipped","statusDetails":"XFAIL Now not work!\n\nAssertionError: Success message(NAME_ITEM_IN_MESSAGE) is presented, but should not be","time":{"start":1742892150884,"stop":1742892151726,"duration":842}},{"uid":"e8bc86e659727f4d","reportUrl":"https://Lexun2.github.io/project_selenium_course/16//#testresult/e8bc86e659727f4d","status":"skipped","statusDetails":"XFAIL Now not work!\n\nAssertionError: Success message(NAME_ITEM_IN_MESSAGE) is presented, but should not be","time":{"start":1742891841354,"stop":1742891843037,"duration":1683}}]},"tags":["@pytest.mark.xfail(reason='Now not work!')"]},"source":"e8b5ae9f0a1eb0eb.json","parameterValues":[]}